name: 🚀 ATM LATAM UI Tests

on:
  workflow_dispatch:

jobs:
  run-ui-tests:
    name: Ejecutar pruebas Playwright + Cucumber
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.8.8'

      - name: Instalar dependencias
        run: mvn clean install -DskipTests

      - name: Ejecutar pruebas con Maven
        run: mvn test

      - name: Guardar resultados como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results/