name: Ejecutar Pruebas Automatizadas LATAM

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Ejecutar pruebas con Maven
        run: mvn clean test

      - name: Instalar Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Generar Reporte Allure
        run: |
          allure generate target/allure-results --clean -o target/allure-report

      - name: Guardar reporte como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/allure-report